# Specify the version of the Compose file format
version: "3.2"

# Define the services/containers to be run
services:
  # Define the web server container
  api:
    platform: linux/amd64
    # Build the image from Dockerfile.api in the current directory
    build:
      context: .
      dockerfile: Dockerfile.api


    # Specify the dependencies
    depends_on:
      - db

    # Define the network to be used
    networks:
      - webnet

  worker:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
    volumes:
      - ./worker.py:/app/worker.py
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: d2c6pb7ibkfkqi
      POSTGRES_USER: uatsuu41pr76d
      POSTGRES_PASSWORD: p46894c0592f823ef3eccd143e829946367ac14217426ef8b61b363bcef6d024d
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
# Define the networks to be used
networks:
  webnet:

# Define the volumes to be used
volumes:
  postgres_data:
